// Export only the specific icons used in the application
import AddIcon from "@mui/icons-material/Add";
import RemoveIcon from "@mui/icons-material/Remove";
import InfoIcon from "@mui/icons-material/Info";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import HomeIcon from "@mui/icons-material/Home";
import BoltRoundedIcon from "@mui/icons-material/BoltRounded";
import SaveAltIcon from "@mui/icons-material/SaveAlt";
import SpaIcon from "@mui/icons-material/Spa";
import AttachMoneyIcon from "@mui/icons-material/AttachMoney";
import WarningIcon from "@mui/icons-material/Warning";
import PrintIcon from "@mui/icons-material/Print";
import ShareIcon from "@mui/icons-material/Share";
import CalculateIcon from "@mui/icons-material/Calculate";
import SavingsIcon from "@mui/icons-material/Savings";
import BuildIcon from "@mui/icons-material/Build";
import TableChartIcon from "@mui/icons-material/TableChart";
import LocationOnIcon from "@mui/icons-material/LocationOn";
import MonetizationOnIcon from "@mui/icons-material/MonetizationOn";
import SavingsOutlinedIcon from "@mui/icons-material/SavingsOutlined";
import ElectricMeterIcon from "@mui/icons-material/ElectricMeter";
import BarChartIcon from "@mui/icons-material/BarChart";
import TimelineIcon from "@mui/icons-material/Timeline";
import PieChartIcon from "@mui/icons-material/PieChart";
import AirIcon from "@mui/icons-material/Air";
import KitchenIcon from "@mui/icons-material/Kitchen";
import ShowerIcon from "@mui/icons-material/Shower";
import LightbulbIcon from "@mui/icons-material/Lightbulb";
import TvIcon from "@mui/icons-material/Tv";
import LocalLaundryServiceIcon from "@mui/icons-material/LocalLaundryService";
import ComputerIcon from "@mui/icons-material/Computer";
import PictureAsPdfIcon from "@mui/icons-material/PictureAsPdf";
import TrendingUpIcon from "@mui/icons-material/TrendingUp";
import CheckCircleOutlineIcon from "@mui/icons-material/CheckCircleOutline";
import NaturePeopleIcon from "@mui/icons-material/NaturePeople";
import FlashOnIcon from "@mui/icons-material/FlashOn";
import EmojiEventsIcon from "@mui/icons-material/EmojiEvents";
import GroupIcon from "@mui/icons-material/Group";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";

export const Add = AddIcon;
export const Remove = RemoveIcon;
export const Info = InfoIcon;
export const ArrowForward = ArrowForwardIcon;
export const ArrowBack = ArrowBackIcon;
export const Home = HomeIcon;
export const BoltRounded = BoltRoundedIcon;
export const SaveAlt = SaveAltIcon;
export const Eco = SpaIcon;
export const AttachMoney = AttachMoneyIcon;
export const Warning = WarningIcon;
export const Print = PrintIcon;
export const Share = ShareIcon;
export const Calculate = CalculateIcon;
export const Savings = SavingsIcon;
export const Build = BuildIcon;
export const TableChart = TableChartIcon;
export const LocationOn = LocationOnIcon;
export const MonetizationOn = MonetizationOnIcon;
export const SavingsOutlined = SavingsOutlinedIcon;
export const ElectricMeter = ElectricMeterIcon;
export const BarChart = BarChartIcon;
export const Timeline = TimelineIcon;
export const PieChart = PieChartIcon;
export const Air = AirIcon;
export const Kitchen = KitchenIcon;
export const Shower = ShowerIcon;
export const Lightbulb = LightbulbIcon;
export const Tv = TvIcon;
export const LocalLaundryService = LocalLaundryServiceIcon;
export const Computer = ComputerIcon;
export const PictureAsPdf = PictureAsPdfIcon;
export const TrendingUp = TrendingUpIcon;
export const CheckCircleOutline = CheckCircleOutlineIcon;
export const NaturePeople = NaturePeopleIcon;
export const FlashOn = FlashOnIcon;
export const EmojiEvents = EmojiEventsIcon;
export const Group = GroupIcon;
export const InfoOutlined = InfoOutlinedIcon;
